// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repositories

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DeleteProduct(ctx context.Context, productID pgtype.UUID) error
	InsertOrder(ctx context.Context, arg InsertOrderParams) error
	InsertProduct(ctx context.Context, arg InsertProductParams) error
	InsertRole(ctx context.Context, arg InsertRoleParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	InsertWarehouse(ctx context.Context, arg InsertWarehouseParams) error
	SelectOneOrder(ctx context.Context, orderID pgtype.UUID) (SelectOneOrderRow, error)
	SelectOneProduct(ctx context.Context, productID pgtype.UUID) (SelectOneProductRow, error)
	SelectOneUserByEmail(ctx context.Context, email string) (SelectOneUserByEmailRow, error)
	SelectOneUserById(ctx context.Context, userID pgtype.UUID) (SelectOneUserByIdRow, error)
	SelectOneUserByRoleId(ctx context.Context, userRoleID pgtype.UUID) (SelectOneUserByRoleIdRow, error)
	SelectOrders(ctx context.Context) ([]SelectOrdersRow, error)
	SelectProducts(ctx context.Context) ([]SelectProductsRow, error)
	SelectRoles(ctx context.Context) ([]SelectRolesRow, error)
	SelectSumQuantityProductsByLocation(ctx context.Context, locationID pgtype.UUID) (int64, error)
	SelectUserByRole(ctx context.Context, uniqueName UserRole) ([]SelectUserByRoleRow, error)
	SelectWarehouses(ctx context.Context) ([]SelectWarehousesRow, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateProductQuantity(ctx context.Context, arg UpdateProductQuantityParams) error
}

var _ Querier = (*Queries)(nil)
